version: 2.1

jobs:
  tests:
    machine:
      docker_layer_caching: true
    steps:
      - run:
          command: sudo apt-get update && apt-get install -y coreutils
          name: Install dependencies
      - checkout
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  main:
    jobs:
      - tests
