version: 2.1

jobs:
  tests:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  main:
    jobs:
      - tests
